In [1]:
import pandas
import rsgislib.tools.utils

In [2]:
input_file = "Mangrove in WDPA July 2022.xlsx"

In [3]:
cntry_stats_df = pandas.read_excel(input_file)

In [4]:
cntry_stats_df["Country"] = ""
cntry_stats_df["UNRegion"] = ""
cntry_stats_df["ReportRegion"] = ""

In [5]:
cntry_stats_df = cntry_stats_df[cntry_stats_df["ISO_TER"] != "GLOBAL"]

In [6]:
cntry_stats_df

,ISO_TER,TOTAL MANGROVE AREA(HA),MANGROVE AREA PROTECTED(HA),PERCENT PROTECTED,Country,UNRegion,ReportRegion
0,ABW,45.938704,1.0,0.021768,,,
1,AGO,28356.673109,146.0,0.005149,,,
2,AIA,3.700790,0.0,0.000000,,,
3,ARE,7444.860192,1323.0,0.177706,,,
4,ASM,32.050071,0.0,0.000000,,,
...,...,...,...,...,...,...,...
117,VUT,1583.671258,0.0,0.000000,,,
118,WLF,29.362414,0.0,0.000000,,,
119,WSM,232.184171,45.0,0.193812,,,
120,YEM,1550.605671,14.0,0.009029,,,
121,ZAF,2643.174222,1005.0,0.380225,,,

In [7]:
cntry_names_lut_file = "gadm_lut.json"
cntry_unregion_lut_file = "country_unregions_lut.json"
cntry_rep_region_lut_file = "country_report_regions_lut.json"

In [8]:
cntry_names_lut = rsgislib.tools.utils.read_json_to_dict(cntry_names_lut_file)
cntry_unregion_lut = rsgislib.tools.utils.read_json_to_dict(cntry_unregion_lut_file)
cntry_rep_region_lut = rsgislib.tools.utils.read_json_to_dict(cntry_rep_region_lut_file)

In [9]:
cntry_unregion_rvs_lut = dict()

for rgn in cntry_unregion_lut:
    for cntry in cntry_unregion_lut[rgn]:
        cntry_unregion_rvs_lut[cntry] = rgn

In [10]:
cntry_report_region_rvs_lut = dict()

for rgn in cntry_rep_region_lut:
    for cntry in cntry_rep_region_lut[rgn]:
        cntry_report_region_rvs_lut[cntry] = rgn

In [11]:
for index, row in cntry_stats_df.iterrows():
    cntry_stats_df.at[index,'Country'] = cntry_names_lut["gid"][row["ISO_TER"]]
    cntry_stats_df.at[index,'UNRegion'] = cntry_unregion_rvs_lut[cntry_names_lut["gid"][row["ISO_TER"]]]
    cntry_stats_df.at[index,'ReportRegion'] = cntry_report_region_rvs_lut[cntry_names_lut["gid"][row["ISO_TER"]]]

In [12]:
cntry_stats_df

,ISO_TER,TOTAL MANGROVE AREA(HA),MANGROVE AREA PROTECTED(HA),PERCENT PROTECTED,Country,UNRegion,ReportRegion
0,ABW,45.938704,1.0,0.021768,Aruba,Car,North_Central_America_Caribbean
1,AGO,28356.673109,146.0,0.005149,Angola,MAf,West_Central_Africa
2,AIA,3.700790,0.0,0.000000,Anguilla,Car,North_Central_America_Caribbean
3,ARE,7444.860192,1323.0,0.177706,United Arab Emirates,WAs,Middle_East
4,ASM,32.050071,0.0,0.000000,American Samoa,Pol,PacificIslands
...,...,...,...,...,...,...,...
117,VUT,1583.671258,0.0,0.000000,Vanuatu,Mel,PacificIslands
118,WLF,29.362414,0.0,0.000000,Wallis and Futuna,Pol,PacificIslands
119,WSM,232.184171,45.0,0.193812,Samoa,Pol,PacificIslands
120,YEM,1550.605671,14.0,0.009029,Yemen,WAs,Middle_East
121,ZAF,2643.174222,1005.0,0.380225,South Africa,SAf,East_Southern_Africa

In [13]:
report_region_stats_df = cntry_stats_df.groupby("ReportRegion").sum()

/var/folders/rq/rrjbs1qs2f52j6hv3g0gyvkm0000gq/T/ipykernel_23627/2731401093.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  report_region_stats_df = cntry_stats_df.groupby("ReportRegion").sum()

In [14]:
report_region_stats_df

,TOTAL MANGROVE AREA(HA),MANGROVE AREA PROTECTED(HA),PERCENT PROTECTED
ReportRegion,,,
Australia_NewZealand,1.046689e+06,496179.000,0.561265
East_Asia,2.277495e+04,2321.000,1.536586
East_Southern_Africa,7.636402e+05,326374.000,6.828883
Middle_East,2.853875e+04,12828.000,2.497704
North_Central_America_Caribbean,2.282695e+06,1525607.375,18.739634
PacificIslands,6.051231e+05,59013.000,4.022792
South_America,2.037810e+06,1461086.000,4.650323
South_Asia,9.549307e+05,502592.000,1.696947
Southeast_Asia,4.822225e+06,1067725.000,3.065281
West_Central_Africa,2.171473e+06,674995.000,8.303631

In [15]:
report_region_stats_df["PERCENT PROTECTED"] = (report_region_stats_df["MANGROVE AREA PROTECTED(HA)"] / report_region_stats_df["TOTAL MANGROVE AREA(HA)"])*100


report_region_stats_df["MANGROVE AREA PROTECTED(km2)"] = (report_region_stats_df["MANGROVE AREA PROTECTED(HA)"] / 100)
report_region_stats_df["TOTAL MANGROVE AREA(km2)"] = (report_region_stats_df["TOTAL MANGROVE AREA(HA)"] / 100)

In [16]:
report_region_stats_df = report_region_stats_df.reset_index()
report_region_stats_df.to_feather("protected_area_proportions_regions.feather")
report_region_stats_df.to_csv("protected_area_proportions_regions.csv")
excel_sheet = 'protect_regions'
xls_writer = pandas.ExcelWriter("protected_area_proportions_regions.xlsx", engine='xlsxwriter')
report_region_stats_df.to_excel(xls_writer, sheet_name=excel_sheet)
xls_writer.save()

/var/folders/rq/rrjbs1qs2f52j6hv3g0gyvkm0000gq/T/ipykernel_23627/1056406321.py:7: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  xls_writer.save()